# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Swift 6.1.0
        uses: swiftdocorg/setup-swift@v1
        with:
          swift-version: "6.1.0"

      - name: Check Swift version
        run: swift --version

      - name: Build package
        run: swift build --build-tests
